[options]
resize_grip = false
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
visible_bell = true
mouse_autohide = false
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
font = Inconsolata 12
#font = Consolas 12
scrollback_lines = 10000
search_wrap = true
#icon_name = terminal

# 0.0: opaque, 1.0: transparent
transparency = 0.0

# "system", "on" or "off"
cursor_blink = off

# "block", "underline" or "ibeam"
cursor_shape = block

# $BROWSER is used by default
browser = firefox

# termite has the correct terminfo, but some applications hardcode TERM checks
#term = termite

[colors]
foreground = #dcdccc
foreground_bold = #ffffff
#foreground_dim = #888888
background = #0f0d0f
cursor = #00ff00

# colors from color0 to color254 can be set
# Black
color0 = #0f0d0f
color8 = #383838

# Red
color1 = #8c1212
color9 = #c72c2c

# Green
color2 = #0d7326
color10 = #25b82f

# Yellow
color3 = #7a8f1a
color11 = #b3cc0e

# Blue
color4 = #434fd1
color12 = #205ad6

# Magenta
color5 = #92099e
color13 = #db2ec4

# Cyan
color6 = #17657d
color14 = #2296ba

# White
color7 = #969696
color15 = #dbdbdb
